name: CI QA – league-auth-service

on:
  push:
    branches: [qa]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: qa

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/${{ secrets.EC2_USER }}

            if [ -d league-auth-service ]; then
              cd league-auth-service
              git reset --hard
              git clean -fd
              git fetch origin
              git checkout qa
              git reset --hard origin/qa
            else
              git clone --branch qa https://github.com/league-platform/league-auth-service.git
              cd league-auth-service
            fi

            # Crear .env con variables
            echo "MONGO_URI=${{ secrets.MONGO_URI }}" > .env
            echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
            echo "PORT=3000" >> .env

            # Construir y correr el contenedor
            docker stop league-auth-service || true
            docker rm league-auth-service || true
            docker build -t league-auth-service .
            docker run -d \
              --name league-auth-service \
              --env-file .env \
              -p 3000:3000 \
              --restart unless-stopped \
              league-auth-service
