name: CI QA – league-auth-service

on:
  push:
    branches: [qa]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: qa

    steps:
      # Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Deploy the app to EC2 using appleboy SSH action
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/${{ secrets.EC2_USER }}

            # Clonación con token privado si el repo es privado
            if [ -d league-auth-service ]; then
              cd league-auth-service
              git pull
            else
              git clone https://${{ secrets.PRIVATE_REPO_TOKEN }}@github.com/league-platform/league-auth-service.git
              cd league-auth-service
            fi

            # Variables de entorno
            echo "MONGO_URI=${{ secrets.MONGO_URI }}" > .env
            echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
            echo "PORT=3000" >> .env

            # Instalar Node.js con permisos
            if ! command -v node &> /dev/null; then
              curl -fsSL https://rpm.nodesource.com/setup_18.x | sudo bash -
              sudo yum install -y nodejs
            fi

            # Instalar dependencias y PM2
            npm install
            sudo npm install -g pm2

            # Ejecutar app con PM2
            pm2 start /home/ec2-user/league-auth-service/src/index.js --name auth-service
            pm2 save
            sudo su -c "env PATH=$PATH:/usr/bin pm2 startup systemd -u $USER --hp /home/$USER"


