name: CI QA – league-auth-service

on:
  push:
    branches: [qa]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: qa

    steps:
      # Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Deploy the app to EC2 using appleboy SSH action
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/${{ secrets.EC2_USER }}

            if [ -d league-auth-service ]; then
              cd league-auth-service
              git pull
            else
              git clone https://github.com/league-platform/league-auth-service.git
              cd league-auth-service
            fi

            echo "MONGO_URI=${{ secrets.MONGO_URI }}" > .env
            echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
            echo "PORT=3000" >> .env

            if ! command -v node &> /dev/null; then
              curl -sL https://rpm.nodesource.com/setup_18.x | bash -
              yum install -y nodejs
            fi

            npm install
            npm install -g pm2
            pm2 start index.js --name auth-service || pm2 restart auth-service
            pm2 save
            pm2 startup | tail -n 1 | bash
